server:
  port: 8085

spring:
  application:
    name: spring-cloud-security

  datasource:
    url: jdbc:mysql://localhost:3306/nacos-security?characterEncoding=utf8
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8858,127.0.0.1:8868
        username: nacos
        password: nacos

logging:
  level:
    root: info