server:
  port: 8085
  servlet:
    context-path: /spring-cloud-alibaba-nacos-discovery-service-security

spring:
  application:
    name: spring-cloud-alibaba-nacos-discovery-service-security

  datasource:
    url: jdbc:mysql://localhost:3306/nacos-security?characterEncoding=utf8
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: nacos1:8848,nacos2:8848,nacos3:8848
        username: nacos
        password: nacos

logging:
  level:
    root: info