server:
  port: 8084

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: AuthenticationService
          uri: lb://spring-cloud-security
          predicates:
            - Path=/auth/{segment}
          filters:
            - SetPath=/auth/{segment}/v1
        - id: UserService
          uri: lb://spring-cloud-user-service
          predicates:
            - Path=/user/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8858,127.0.0.1:8868
        username: nacos
        password: nacos
