server:
  port: 8084

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: route1
          uri: lb://spring-cloud-security
          predicates:
            - Path=/*/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8858,127.0.0.1:8868
        username: nacos
        password: nacos
