server:
  port: 8089
spring:
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: 1000
    timeout: 6000
  application:
    name: spring-cloud-redis-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql://localhost:3306/nacos-security?characterEncoding=utf8
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update