server:
  port: 8086

spring:
  application:
    name: spring-cloud-user-service

  datasource:
    url: jdbc:mysql://localhost:3306/nacos-security?characterEncoding=utf8
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #,127.0.0.1:8858,127.0.0.1:8868
        username: nacos
        password: nacos
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    discovery-client-enabled: false
    base-url: http://127.0.0.1:9411
    sender:
      type: web
logging:
  level:
    root: info